# Generated by Django 4.0.3 on 2022-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srollno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('smarks', models.FloatField()),
                ('saddress', models.CharField(max_length=100)),
            ],
        ),
    ]
